<?php

namespace SAFETECHio\FIDO2\WebAuthn\Protocol\Options;

/** See https://www.w3.org/TR/webauthn/#attestation-convey */
class ConveyancePreference
{
    /**
     * The default value. This value indicates that the Relying Party is not interested in authenticator attestation. For example,
     * in order to potentially avoid having to obtain user consent to relay identifying information to the Relying Party, or to
     * save a roundtrip to an Attestation CA.
     */
    const PreferNoAttestation = "none";

    /**
     * This value indicates that the Relying Party prefers an attestation conveyance yielding verifiable attestation
     * statements, but allows the client to decide how to obtain such attestation statements. The client MAY replace
     * the authenticator-generated attestation statements with attestation statements generated by an Anonymization
     * CA, in order to protect the user’s privacy, or to assist Relying Parties with attestation verification in a
     * heterogeneous ecosystem.
     */
    const PreferIndirectAttestation = "indirect";

    /**
     * This value indicates that the Relying Party wants to receive the attestation statement as generated by the authenticator.
     */
    const PreferDirectAttestation = "direct";
}